server:
  port: 8084
spring:
    application:
      name: gateway
      cloud:
          gateway:
              routes:
                  - id: usuario
                    uri: lb://usuario
                    predicates:
                    - Path=/usuario/**
                  - id: lista-service
                    uri: lb://lista-service
                    predicates:
                    - Path=/lista-service/**


# server.port=8084
# spring.application.name=gateway
# spring.application.name=gateway