spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todogether?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {CLIENT_ID}
            client-secret: {CLIENT_SECRET}
            scope:
              - email
              - profile

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE