spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todogether?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 560799140281-2jk79qnss2gtu7s6crrcl70d0idm11k1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE